### PR TITLE
Adding 'full=True' to crossrefdb attribute in CrossRefResource in api.py

### PR DESCRIPTION
**Pull request by rzelayafavila**
Very small PR. This was needed so that the crossrefdb attribute in the CrossRefResource also displays the name and url of the crossreference database.

### CODE REVIEW

**Review by dongbohu — APPROVED** [review]
Looks good!

**Comment by rzelayafavila** [comment]
Thanks @dongbohu! I also noticed that we had not switched the .hgignore file to a .gitignore file with the corresponding syntax, so I added that as well (which is also a small change). Does that change look good to you too?

**Review by dongbohu — APPROVED** [review]
Good idea. Approved again!

**Comment by rzelayafavila** [comment]
Ok, thanks @dongbohu! Merging!

**Comment by mhuyck** [comment]
Heh... you're done already, but for the record I also approve. 👍

**Pull request merged**
